version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    shm_size: '8g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python -m scripts.train_mask2former_segmentation